#Hellowhale-Deployment.yml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellowhale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-whale-app
      version: blue
  template:
    metadata:
      name: hello-whale-pod
      labels:
        app: hello-whale-app
        version: blue
    spec:
      containers:
      - name: hello-whale-container
        image: vamsijakkula/hello-blue-whale:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
